package ApiHelper;

import java.util.HashMap;

public class Language {
    public HashMap<String,String> langMappings = new HashMap<>(){{
        put("English","en");
        put("Abkhaz","ab");
        put("Afrikaans","af");
        put("Afar","aa");
        put("Akan","ak");
        put("Albanian","ak");
        put("Amharic","am");
        put("Arabic","ar");
        put("Aragonese","an");
        put("Armenian","hy");
        put("Assamese","as");
        put("Avaric","av");
        put("Avestan","ae");
        put("Aymara","ay");
        put("Azerbaijani","az");
        put("Bambara","bm");
        put("Bashkir","ba");
        put("Belarusian","be");
        put("Bengali","bn");
        put("Bihari","bh");
        put("Bislama","bi");
        put("Bosnian","bs");
        put("Breton","br");
        put("Bulgarian","bg");
        put("Burmese","my");
        put("Catalan","ca");
        put("Chamorro","ch");
        put("Chechen","ce");
        put("Chichewa, Chewa, Nyanja","ny");
        put("Chinese (Simplified)","zh");
        put("Chinese (Traditional)","zh-hant");
        put("Chuvash","cv");
        put("Cornish","kw");
        put("Corsican","co");
        put("Cree","cr");
        put("Croatian","hr");
        put("Czech","cs");
        put("Danish","da");
        put("Divehi, Dhivehi, Maldivian","dv");
        put("Dutch","nl");
        put("Dzongkha","dz");
        put("Esperanto","eo");
        put("Estonian","et");
        put("Ewe","ee");
        put("Faroese","fo");
        put("Fijian","fj");
        put("Finnish","fi");
        put("French","fr");
        put("Fulah","ff");
        put("Galician","gl");
        put("Ganda","lg");
        put("Georgian","ka");
        put("German","de");
        put("Greek","el");
        put("Guaraní","gn");
        put("Gujarati","gu");
        put("Haitian, Haitian Creole","ht");
        put("Hausa","ha");
        put("Hebrew","he");
        put("Herero","hz");
        put("Hindi","hi");
        put("Hiri Motu","ho");
        put("Hungarian","hu");
        put("Icelandic","is");
        put("Ido","io");
        put("Igbo","ig");
        put("Indonesian","id");
        put("Interlingua","ia");
        put("Interlingue","ie");
        put("Inuktitut","iu");
        put("Inupiaq","ik");
        put("Irish","ga");
        put("Italian","it");
        put("Japanese","ja");
        put("Javanese","jv");
        put("Kalaallisut","kl");
        put("Kannada","kn");
        put("Kanuri","kr");
        put("Kashmiri","ks");
        put("Kazakh","kk");
        put("Khmer","km");
        put("Kikuyu","ki");
        put("Kinyarwanda","rw");
        put("Kirghiz","ky");
        put("Komi","kv");
        put("Kongo","kg");
        put("Korean","ko");
        put("Kurdish","ku");
        put("Kwanyama, Kuanyama","kj");
        put("Lao","lo");
        put("Latin","la");
        put("Latvian","lv");
        put("Limburgish, Limburgan, Limburger","li");
        put("Lingala","ln");
        put("Lithuanian","lt");
        put("Luba-Katanga","lu");
        put("Luxembourgish, Letzeburgesch","lb");
        put("Macedonian","mk");
        put("Malagasy","mg");
        put("Malay","ms");
        put("Malayalam","ml");
        put("Maltese","mt");
        put("Manx","gv");
        put("Marathi","mr");
        put("Marshallese","mh");
        put("Mongolian","mn");
        put("Māori","mi");
        put("Nauru","na");
        put("Navajo, Navaho","nv");
        put("Ndonga","ng");
        put("Nepali","ne");
        put("North Ndebele","nd");
        put("Northern Sami","se");
        put("Norwegian","no");
        put("Norwegian Bokmål","nb");
        put("Norwegian Nynorsk","nn");
        put("Occitan","oc");
        put("Ojibwe, Ojibwa","oj");
        put("Old Church Slavonic, Church Slavonic, Old Bulgarian","cu");
        put("Oriya","or");
        put("Oromo","om");
        put("Ossetian, Ossetic","os");
        put("Pashto","ps");
        put("Persian","fa");
        put("Polish","pl");
        put("Portuguese","pt");
        put("Punjabi","pa");
        put("Pāli","pi");
        put("Quechua","qu");
        put("Romanian","ro");
        put("Romansh","rm");
        put("Rundi","rn");
        put("Russian","ru");
        put("Samoan","sm");
        put("Sango","sg");
        put("Sanskrit (Saṁskṛta)","sa");
        put("Sardinian","sc");
        put("Scottish Gaelic, Gaelic","gd");
        put("Serbian","sr");
        put("Shona","sn");
        put("Sichuan Yi","ii");
        put("Sindhi","sd");
        put("Sinhala","si");
        put("Slovak","sk");
        put("Slovenian","sl");
        put("Somali","so");
        put("Southern Ndebele","nr");
        put("Southern Sotho","st");
        put("Spanish","es");
        put("Sundanese","su");
        put("Swahili","sw");
        put("Swati","ss");
        put("Swedish","sv");
        put("Tagalog","tl");
        put("Tahitian","ty");
        put("Tajik","tg");
        put("Tamil","ta");
        put("Tatar","tt");
        put("Telugu","te");
        put("Thai","th");
        put("Tibetan","bo");
        put("Tigrinya","ti");
        put("Tongan","to");
        put("Tsonga","ts");
        put("Tswana","tn");
        put("Turkish","tr");
        put("Turkmen","tk");
        put("Twi","tw");
        put("Ukrainian","uk");
        put("Urdu","ur");
        put("Uyghur, Uighur","ug");
        put("Uzbek","uz");
        put("Venda","ve");
        put("Vietnamese","vi");
        put("Volapük","vo");
        put("Walloon","wa");
        put("Welsh","cy");
        put("Western Frisian","fy");
        put("Wolof","wo");
        put("Xhoso","xh");
        put("Yiddish","yi");
        put("Yoruba","yo");
        put("Zhuang, Chuang","za");
        put("Zulu","zu");
    }};
}
